version: '3.7'
services:
    backend:
        image: infra_api:latest
        container_name: backend
        networks:
          - utm_automation
        command: python manage.py runserver_plus 0.0.0.0:8001 --cert-file ./certs/cert.pem --key-file ./certs/key.pem

        ports:
            - "8001:8001"
        depends_on:
           - redis


    queue_executor:
        image: queue_executer:latest
        container_name: queue_executer
        networks:
          - utm_automation
        depends_on:
          - redis

    redis:
        image: redis:latest
        container_name: reids
        ports:
          - "6379:6379"
        networks:
          - utm_automation

networks:
    utm_automation:
        name: utm_automation
